- name: app set up
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: java
  ansible.builtin.import_role:
    name: common
    tasks_from: java

- name: mongodb set up
  ansible.builtin.import_role:
    name: common
    tasks_from: mongodb-setup

- name: systemctl service
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd